### ISSUE TITLE
Set up the project

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#1]
- create starting pom-file
- set up 0pdd integration
- add Github actions

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#2](https://github.com/Decision-Driven-Development/logic-checker/issues/2) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#2](https://github.com/Decision-Driven-Development/logic-checker/issues/2) is solved here.
