### ISSUE TITLE
See the index page with current stored state

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#10]
The index page of the web UI should output all the current state for the application. For now it should be something simple, probably, just text area or multiple nested lists.

For the initial page rendering we can use the first test file in the tests folder.

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#12](https://github.com/Decision-Driven-Development/logic-checker/issues/12), [#13](https://github.com/Decision-Driven-Development/logic-checker/issues/13) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 5 puzzles [#12](https://github.com/Decision-Driven-Development/logic-checker/issues/12), [#13](https://github.com/Decision-Driven-Development/logic-checker/issues/13), [#14](https://github.com/Decision-Driven-Development/logic-checker/issues/14), [#15](https://github.com/Decision-Driven-Development/logic-checker/issues/15), [#16](https://github.com/Decision-Driven-Development/logic-checker/issues/16) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#12](https://github.com/Decision-Driven-Development/logic-checker/issues/12), [#13](https://github.com/Decision-Driven-Development/logic-checker/issues/13), [#14](https://github.com/Decision-Driven-Development/logic-checker/issues/14) are still not solved; solved: [#15](https://github.com/Decision-Driven-Development/logic-checker/issues/15), [#16](https://github.com/Decision-Driven-Development/logic-checker/issues/16).

**Comment by 0pdd** [comment]
@nergal-perm all 5 puzzles are solved here: [#12](https://github.com/Decision-Driven-Development/logic-checker/issues/12), [#13](https://github.com/Decision-Driven-Development/logic-checker/issues/13), [#14](https://github.com/Decision-Driven-Development/logic-checker/issues/14), [#15](https://github.com/Decision-Driven-Development/logic-checker/issues/15), [#16](https://github.com/Decision-Driven-Development/logic-checker/issues/16).
