### ISSUE TITLE
Implement an endpoint to run a command

### ISSUE THREAD

**Issue by 0pdd** [Decision-Driven-Development/logic-checker#20]
The puzzle `9-76e7f501` from #9 has to be resolved: 

https://github.com/Decision-Driven-Development/logic-checker/blob/6615bc14217058d1d2d7662a564461f81f9c6edc/src/main/java/ru/ewc/checklogic/server/StatePage.java#L65-L65

The puzzle was created by Евгений Терехов on 18-May-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nergal-perm** [comment]
No arguments yet, just a command

**Comment by 0pdd** [comment]
@0pdd the puzzle [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `9-76e7f501` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21) is solved here.
