### ISSUE TITLE
Use Decita v.0.7.0

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#23]

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#24](https://github.com/Decision-Driven-Development/logic-checker/issues/24) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#24](https://github.com/Decision-Driven-Development/logic-checker/issues/24) is solved here.
