### ISSUE TITLE
Provide request parameters for a Command before performing it (Web UI)

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#25]

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28), [#29](https://github.com/Decision-Driven-Development/logic-checker/issues/29) are still not solved; solved: [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#29](https://github.com/Decision-Driven-Development/logic-checker/issues/29) are still not solved; solved: [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#29](https://github.com/Decision-Driven-Development/logic-checker/issues/29) is still not solved; solved: [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28).

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#29](https://github.com/Decision-Driven-Development/logic-checker/issues/29), [#31](https://github.com/Decision-Driven-Development/logic-checker/issues/31) are still not solved; solved: [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#29](https://github.com/Decision-Driven-Development/logic-checker/issues/29) is still not solved; solved: [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28), [#31](https://github.com/Decision-Driven-Development/logic-checker/issues/31).

**Comment by 0pdd** [comment]
@nergal-perm all 5 puzzles are solved here: [#26](https://github.com/Decision-Driven-Development/logic-checker/issues/26), [#27](https://github.com/Decision-Driven-Development/logic-checker/issues/27), [#28](https://github.com/Decision-Driven-Development/logic-checker/issues/28), [#29](https://github.com/Decision-Driven-Development/logic-checker/issues/29), [#31](https://github.com/Decision-Driven-Development/logic-checker/issues/31).

**Comment by nergal-perm** [comment]
Naive version is ready
