### ISSUE TITLE
Extract all the required parameters from the command's description

### ISSUE THREAD

**Issue by 0pdd** [Decision-Driven-Development/logic-checker#28]
The puzzle `25-de00f783` from #25 has to be resolved: 

https://github.com/Decision-Driven-Development/logic-checker/blob/c075c0ff7f4f018a805817e65d323a4669a338b4/src/main/java/ru/ewc/checklogic/server/CommandPage.java#L75-L75

The puzzle was created by Евгений Терехов on 14-Jun-24. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by nergal-perm** [comment]
One way of doing it involves #17.

Another way could be just getting those arguments from fully parsed command via library call.

**Comment by 0pdd** [comment]
The puzzle `25-de00f783` has disappeared from the source code, that's why I closed this issue.
