### ISSUE TITLE
Fail to load server if started with an empty project

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#33]
While starting a server looking at an empty project folder the java process crashes. 

I would like to open a special page describing the situation and offering to create a basic structure for a project instead. 

Upon clicking on "Create structure" button, the needed folders and `application.yaml` should be created, along with `initialize` command, used to create the initial game state. After that the server should somehow reload all the configuration.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#43](https://github.com/Decision-Driven-Development/logic-checker/issues/43) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#46](https://github.com/Decision-Driven-Development/logic-checker/issues/46) is still not solved; solved: [#43](https://github.com/Decision-Driven-Development/logic-checker/issues/43).

**Comment by 0pdd** [comment]
@nergal-perm all 2 puzzles are solved here: [#43](https://github.com/Decision-Driven-Development/logic-checker/issues/43), [#46](https://github.com/Decision-Driven-Development/logic-checker/issues/46).
