### ISSUE TITLE
Running tests on empty '/states' folder shows generic server error page

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#34]
Need to handle that exception and show an empty `/test` page

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#51](https://github.com/Decision-Driven-Development/logic-checker/issues/51) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#51](https://github.com/Decision-Driven-Development/logic-checker/issues/51) is solved here.
