### ISSUE TITLE
Create a dedicated page for server configuration

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#44]
It's better to set all the server settings from the dedicated page, not from the State Simulation page.

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#56](https://github.com/Decision-Driven-Development/logic-checker/issues/56) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm the only puzzle [#56](https://github.com/Decision-Driven-Development/logic-checker/issues/56) is solved here.
