### ISSUE TITLE
Reduce the number of ServerContext methods

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#52]

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#54](https://github.com/Decision-Driven-Development/logic-checker/issues/54) is still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#54](https://github.com/Decision-Driven-Development/logic-checker/issues/54), [#55](https://github.com/Decision-Driven-Development/logic-checker/issues/55) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm all 2 puzzles are solved here: [#54](https://github.com/Decision-Driven-Development/logic-checker/issues/54), [#55](https://github.com/Decision-Driven-Development/logic-checker/issues/55).

**Comment by nergal-perm** [comment]
After last week's commits Qulice is satisfied with that, issue closed.
