### ISSUE TITLE
Run a command with no arguments via the web UI

### ISSUE THREAD

**Issue by nergal-perm** [Decision-Driven-Development/logic-checker#9]
The flow is as follows:

1. Go to the specific command page directly by typing its URL in the address bar.
2. No request parameters are available to type in
3. The button `Execute` should be in a correct state
4. After pushing the `Execute` button user should return to the updated index page

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#18](https://github.com/Decision-Driven-Development/logic-checker/issues/18), [#19](https://github.com/Decision-Driven-Development/logic-checker/issues/19), [#20](https://github.com/Decision-Driven-Development/logic-checker/issues/20) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 4 puzzles [#18](https://github.com/Decision-Driven-Development/logic-checker/issues/18), [#19](https://github.com/Decision-Driven-Development/logic-checker/issues/19), [#20](https://github.com/Decision-Driven-Development/logic-checker/issues/20), [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21) are still not solved.

**Comment by 0pdd** [comment]
@nergal-perm 2 puzzles [#18](https://github.com/Decision-Driven-Development/logic-checker/issues/18), [#19](https://github.com/Decision-Driven-Development/logic-checker/issues/19) are still not solved; solved: [#20](https://github.com/Decision-Driven-Development/logic-checker/issues/20), [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21).

**Comment by 0pdd** [comment]
@nergal-perm 3 puzzles [#18](https://github.com/Decision-Driven-Development/logic-checker/issues/18), [#19](https://github.com/Decision-Driven-Development/logic-checker/issues/19), [#22](https://github.com/Decision-Driven-Development/logic-checker/issues/22) are still not solved; solved: [#20](https://github.com/Decision-Driven-Development/logic-checker/issues/20), [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21).

**Comment by 0pdd** [comment]
@nergal-perm the puzzle [#18](https://github.com/Decision-Driven-Development/logic-checker/issues/18) is still not solved; solved: [#19](https://github.com/Decision-Driven-Development/logic-checker/issues/19), [#20](https://github.com/Decision-Driven-Development/logic-checker/issues/20), [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21), [#22](https://github.com/Decision-Driven-Development/logic-checker/issues/22).

**Comment by 0pdd** [comment]
@nergal-perm all 5 puzzles are solved here: [#18](https://github.com/Decision-Driven-Development/logic-checker/issues/18), [#19](https://github.com/Decision-Driven-Development/logic-checker/issues/19), [#20](https://github.com/Decision-Driven-Development/logic-checker/issues/20), [#21](https://github.com/Decision-Driven-Development/logic-checker/issues/21), [#22](https://github.com/Decision-Driven-Development/logic-checker/issues/22).
